// Generated by CoffeeScript 1.8.0
(function() {
  var app, http, io;

  app = require('express')();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  exports.index = function(req, res) {
    return res.render("index");
  };

  io.on('connection', function(socket) {
    console.log('a user connected');
    return socket.on('new message', function(data) {
      return socket.broadcast.emit('new message', {
        username: "payne",
        message: "this is a test"
      });
    });
  });

}).call(this);

//# sourceMappingURL=home.js.map
